--1)
SELECT 
    ALUNOS.NOME_ALUNO,
    CURSOS.NOME_CURSO,
    MATRICULAS.NOTA_FINAL
FROM MATRICULAS
INNER JOIN ALUNOS
    ON MATRICULAS.ID_ALUNO = ALUNOS.ID_ALUNO
INNER JOIN CURSOS 
    ON MATRICULAS.ID_CURSO = CURSOS.ID_CURSO;
