SELECT ALUNOS.NOME_ALUNO, 
       ROUND(AVG(MATRICULAS.NOTA_FINAL), 2) AS MEDIA_GERAL
FROM ALUNOS
JOIN MATRICULAS ON ALUNOS.ID_ALUNO = MATRICULAS.ID_ALUNO
GROUP BY ALUNOS.ID_ALUNO, ALUNOS.NOME_ALUNO
ORDER BY MEDIA_GERAL DESC
LIMIT 1;
